USE [master]
GO

/****** Object:  Database [TR3SDETR3S]    Script Date: 25/02/2022 2:32:27 a. m. ******/
CREATE DATABASE [TR3SDETR3S]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TR3SDETR3S', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TR3SDETR3S.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TR3SDETR3S_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TR3SDETR3S_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TR3SDETR3S].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TR3SDETR3S] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TR3SDETR3S] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TR3SDETR3S] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TR3SDETR3S] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TR3SDETR3S] SET ARITHABORT OFF 
GO

ALTER DATABASE [TR3SDETR3S] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TR3SDETR3S] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TR3SDETR3S] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TR3SDETR3S] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TR3SDETR3S] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TR3SDETR3S] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TR3SDETR3S] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TR3SDETR3S] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TR3SDETR3S] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TR3SDETR3S] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TR3SDETR3S] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TR3SDETR3S] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TR3SDETR3S] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TR3SDETR3S] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TR3SDETR3S] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TR3SDETR3S] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TR3SDETR3S] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TR3SDETR3S] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TR3SDETR3S] SET  MULTI_USER 
GO

ALTER DATABASE [TR3SDETR3S] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TR3SDETR3S] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TR3SDETR3S] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TR3SDETR3S] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TR3SDETR3S] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TR3SDETR3S] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TR3SDETR3S] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TR3SDETR3S] SET  READ_WRITE 
GO

